language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
before_script:
  - git config --global user.name 'Travis-CI'
  - git config --global user.email 'travis-ci@design4.pro'
after_success:
  - npm run coverage
