sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
env:
  global:
    - secure: "aeyeengoa8Omahpohj0Yaichahvei6maiwar1ohk5f"
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - npm i -g npm@^2.0.0
before_script:
  - git config --global user.name 'Travis-CI'
  - git config --global user.email 'travis-ci@design4.pro'
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - npm prune
script:
  - npm run build
  - chmod +x ./dist/cli.js
  - npm run cover
  - npm run check-coverage
after_success:
  - npm run report-coverage
  - npm run release -- --no-verify
  - git push --follow-tags origin master
  - npm publish
  - npm run release-github-remove
  - npm run release-github
